name: Build and Deploy
on:
  push:
    branches: [ci-cd]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Build
      run: go build -o miniproject .
    - name: Build Docker image
      run: docker build -t my-docker-image:latest .
      env:
        DOCKER_USERNAME: ${{ deviam7}}
        DOCKER_PASSWORD: ${{ Deviamalia07! }}
    - name: Push Docker image
      uses: docker/login-action@v1
      with:
        username: ${{ deviam7 }}
        password: ${{ Deviamalia07! }}
    - run: docker tag my-docker-image:latest miniproject:1.0
    - run: docker push miniproject:latest
    - run: docker push miniproject:1.0
