name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build and Test
      run: |
        go mod download
        go build -o main
        go test ./...

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.CS_DOCKER_USER }}
        password: ${{ secrets.CS_DOCKER_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker build -t deviapp .
        docker tag deviapp:latest deviam7/deviapp:latest
        docker push deviam7/deviapp:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Install doctl
      run: |
        curl -L https://github.com/digitalocean/doctl/releases/download/v1.64.0/doctl-1.64.0-linux-amd64.tar.gz | tar xvz
        sudo mv doctl /usr/local/bin

    - name: Deploy to Digital Ocean
      env:
        DROPLET_ID: deviapp
      run: |
        doctl auth init --access-token ${{ secrets.CS_DIGITAL_OCEAN_ACCESS_TOKEN }}
        doctl compute ssh $DROPLET_ID --ssh-command 'docker pull deviam7/deviapp:latest'
        doctl compute ssh $DROPLET_ID --ssh-command 'docker stop deviapp-container || true'
        doctl compute ssh $DROPLET_ID --ssh-command 'docker rm deviapp-container || true'
        doctl compute ssh $DROPLET_ID --ssh-command 'docker run -d --name deviapp-container -p 8080:8080 --restart always deviam7/deviapp:latest'
