name: CI
on:
  push:
    branches: ["CI/CD"]

jobs:
  build:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Connect to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.POS_DOCKER_USER }}
          password: ${{ secrets.POS_DOCKER_SECRET }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.POS_DOCKER_USER }}/deviapp-repo:latest

  deployment:
    needs: build
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.POS_SERVER_USERNAME}}
          password: ${{ secrets.POS_SERVER_PW}}
          port: ${{ secrets.POS_SERVER_PORT  }}
          script: |
            whoami
            docker stop deviapp-repo || true && docker rm deviapp-repo || true
            docker pull ${{ vars.IMAGE_NAME }}
            docker run -d -p 1213:1213 --name ${{ vars.CONTAINER_NAME }} ${{ vars.IMAGE_NAME }}