name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip

      - name: Install Ansible
        run: |
          sudo apt-add-repository --yes --update ppa:ansible/ansible
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Deploy to DigitalOcean
        run: |
          ansible-playbook deploy.yml -e 'db_username=doadmin db_password=AVNS_H2AHwsJhR9To34OEkeD db_host=dbaas-db-4459780-do-user-12872560-0.b.db.ondigitalocean.com db_port=25060 db_name=defaultdb db_sslmode=REQUIRED' --private-key ~/.ssh/id_rsa
