---
  - name: Deploy to DigitalOcean
    hosts: 178.128.85.125
    remote_user: root
    vars:
      db_username: doadmin
      db_password: AVNS_H2AHwsJhR9To34OEkeD
      db_host: dbaas-db-4459780-do-user-12872560-0.b.db.ondigitalocean.com
      db_port: 25060
      db_name: defaultdb
      db_sslmode: REQUIRED
    tasks:
      - name: Install MySQL client
        apt:
          name: mysql-client
          state: present
        become: true
  
      - name: Create database user
        mysql_user:
          name: "{{ defaultdb }}"
          password: "{{  }}"
          login_host: "{{ dbaas-db-4459780-do-user-12872560-0.b.db.ondigitalocean.com }}"
          login_port: "{{ 25060 }}"
          login_user: "{{ doadmin }}"
          login_password: "{{ AVNS_H2AHwsJhR9To34OEkeD }}"
          state: present
        become: true
  
      - name: Create database
        mysql_db:
          name: "{{ defaultdb }}"
          collation: utf8_general_ci
          encoding: utf8
          login_host: "{{ dbaas-db-4459780-do-user-12872560-0.b.db.ondigitalocean.com}}"
          login_port: "{{ 25060 }}"
          login_user: "{{ doadmin }}"
          login_password: "{{ AVNS_H2AHwsJhR9To34OEkeD }}"
          state: present
        become: true
  
      # Add your deployment tasks here
  